<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>BadPlaceExecutor.Core</RootNamespace>
    <AssemblyName>BadPlaceExecutor.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\Il2CppAssemblies\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppMoonSharp.Interpreter">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\Il2CppAssemblies\Il2CppMoonSharp.Interpreter.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>C:\Users\SeanS\AppData\Roaming\Polytoria\Client\1.4.151\MelonLoader\Il2CppAssemblies\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
